apiVersion: v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: testmailt46/simple-flask-api:version1.9
      